#!/bin/bash
set -e

echo "=== Generating Daily Standup ==="

DATA=$(cat my-analytics/data.json)
TODAY=$(date -u +%Y-%m-%d)
YESTERDAY=$(date -u -d 'yesterday' +%Y-%m-%d 2>/dev/null || date -u -v-1d +%Y-%m-%d)

TOTAL=$(echo "$DATA" | jq '.total_commits')
REPOS=$(echo "$DATA" | jq '.repos.total')
STREAK=$(echo "$DATA" | jq '.streak')

# Get yesterday's and today's commits
YESTERDAY_COMMITS=$(echo "$DATA" | jq -r --arg d "$YESTERDAY" '[.recent_commits // [] | .[] | select(.date[0:10] == $d) | select(.message | test("\\[automated\\]") | not) | "\(.repo): \(.message)"] | if length == 0 then "No commits" else join("; ") end')
TODAY_COMMITS=$(echo "$DATA" | jq -r --arg d "$TODAY" '[.recent_commits // [] | .[] | select(.date[0:10] == $d) | select(.message | test("\\[automated\\]") | not) | "\(.repo): \(.message)"] | if length == 0 then "No commits yet" else join("; ") end')
TOP_REPOS=$(echo "$DATA" | jq -r '[.recent_commits // [] | .[].repo] | group_by(.) | [.[] | {r: .[0], c: length}] | sort_by(-.c) | .[0:5] | [.[] | "\(.r) (\(.c))"] | join(", ")')

echo "Today: $TODAY"
echo "Total commits: $TOTAL"
echo "Streak: $STREAK"
echo "Yesterday commits: $YESTERDAY_COMMITS"

# Build prompt
PROMPT=$(cat <<PROMPT_END
Generate a daily standup for Akhil, solo founder at Keeda Studios.

Date: $TODAY
Total commits: $TOTAL across $REPOS repos
Streak: $STREAK days
Yesterday commits: $YESTERDAY_COMMITS
Today commits: $TODAY_COMMITS
Active repos: $TOP_REPOS
Projects: Thulaa (card game, 150 DAU), Hinglish Vinglish (language app, 300 users), Vibe Lingo (launching), Mali (next week), WordKO, Bird City, BGMF (Apple blocked)

Return ONLY valid JSON:
{"date":"$TODAY","yesterday":["item1","item2"],"today":["item1","item2"],"blockers":["item"],"metrics":["metric1","metric2"]}

Be specific. Reference actual repos and commits. No markdown.
PROMPT_END
)

# Call Claude API
echo "Calling Claude API..."
BODY=$(jq -n --arg p "$PROMPT" '{model:"claude-sonnet-4-20250514",max_tokens:1024,messages:[{role:"user",content:$p}]}')

RESPONSE=$(curl -s https://api.anthropic.com/v1/messages \
  -H "Content-Type: application/json" \
  -H "x-api-key: $ANTHROPIC_API_KEY" \
  -H "anthropic-version: 2023-06-01" \
  -d "$BODY")

STANDUP=$(echo "$RESPONSE" | jq -r '.content[0].text // empty')

if [ -z "$STANDUP" ]; then
  echo "Claude API failed, using fallback"
  echo "$RESPONSE" | jq . 2>/dev/null || echo "$RESPONSE"
  STANDUP="{\"date\":\"$TODAY\",\"yesterday\":[\"Active development across repos\",\"$TOTAL total commits\"],\"today\":[\"Continuing builds\"],\"blockers\":[],\"metrics\":[\"$TOTAL commits\",\"$STREAK day streak\"]}"
fi

if echo "$STANDUP" | jq . > /dev/null 2>&1; then
  echo "$STANDUP" | jq . > my-analytics/standup.json
  echo "Standup written:"
  cat my-analytics/standup.json
else
  echo "Invalid JSON, using fallback"
  echo "{\"date\":\"$TODAY\",\"yesterday\":[\"Active development\"],\"today\":[\"Continuing builds\"],\"blockers\":[],\"metrics\":[\"$TOTAL commits\",\"$STREAK day streak\"]}" | jq . > my-analytics/standup.json
fi

# === TTS Narration ===
echo ""
echo "=== Generating TTS Narration ==="

TEXT="Hey, I'm Akhil. Here's my work rate, live from GitHub. Since October 2024, I've made $TOTAL commits across $REPOS repositories. All solo, from idea to app store. My current shipping streak is $STREAK consecutive days. I shipped 6 apps in 17 months. My fastest time to market was 3 weeks for Hinglish Vinglish, a Hindi learning app I built for my wife. Thulaa, my card game, hit 3,000 downloads with 54 percent day 7 retention after I trained AI bots using Monte Carlo Tree Search. A viral reel hit 2 million views. I build autonomous agents for influencer outreach, daily analytics, and content generation. This entire page updates automatically. The data is real. And this voice is generated by ElevenLabs. If you're building something real and need someone who ships, let's talk."

echo "Calling ElevenLabs TTS API..."
curl -s "https://api.elevenlabs.io/v1/text-to-speech/21m00Tcm4TlvDq8ikWAM" \
  -H "Content-Type: application/json" \
  -H "xi-api-key: $ELEVENLABS_API_KEY" \
  -d "$(jq -n --arg t "$TEXT" '{text:$t,model_id:"eleven_multilingual_v2",voice_settings:{stability:0.5,similarity_boost:0.75,style:0.3}}')" \
  --output my-analytics/narration.mp3

FILE_SIZE=$(stat -c%s my-analytics/narration.mp3 2>/dev/null || stat -f%z my-analytics/narration.mp3 2>/dev/null || echo "0")
if [ "$FILE_SIZE" -gt 1000 ]; then
  echo "TTS narration generated: ${FILE_SIZE} bytes"
else
  echo "TTS may have failed (${FILE_SIZE} bytes)"
  cat my-analytics/narration.mp3 2>/dev/null
  rm -f my-analytics/narration.mp3
fi

echo ""
echo "=== Done ==="
